components/BackBtn.js
components/DeleteBtn.js
components/GenericPopUp.js
screens/CreateAccFormScreen.js
screens/LoginScreen.js
screens/ProductEditScreen.js
screens/ProductFormScreen.js
screens/ProductRow.js

> increased touchable area in Back button.
> introduced Delete button component bundled with pop up for action confirmation.
> add accordion open delay and auto close swipe left gesture when button is pressed.

Added Delete product function in Edit Product screen.

---

App.js
README.md
components/InputText.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
package-lock.json
package.json
screens/CreateAccFormScreen.js
screens/CreateAccScreen.js
screens/HomeScreen.js
screens/IntroAppScreen.js
screens/Login.js
screens/LoginScreen.js
screens/LoginSuccessScreen.js
screens/SettingsScreen.js
screens/StaffFormScreen.js

> updated LoginScreen to use KeyboardAvoidingView.
> do not auto capitalize staff username in StaffFormScreen.

Implement multi language feature using expo-localization and i18n-js.

---

actions/productoptions.js
components/RNSwitch.js
constants/Backend.js
screens/CategoryCustomize.js
screens/CategoryCustomizeScreen.js
screens/ClientUserLoginForm.js
screens/ClockIn.js
screens/ProductEditScreen.js
screens/ProductFormScreen.js
screens/ProductRow.js

> fixed scroll bar in the center issue.
> refactored Backend.js.

get product options by label in Edit Product screen.

---

actions/tablelayouts.js
components/EditPasswordPopUp.js
constants/Backend.js
locales/en.js
locales/zh.js
screens/BackendErrorScreen.js
screens/PrinterForm.js
screens/PrinternKDS.js
screens/SettingsScreen.js
screens/ShiftClose.js
screens/TableForm.js
screens/TableLayoutAdd.js
screens/TableLayoutForm.js
screens/WorkingAreaForm.js

> added i18n to working area/printer and table layouts.
> updated manage shift screen.

Refactored table layout management

---

actions/custom.js
actions/shift.js
components/ConfirmActionButton.js
components/DropDown.js
constants/Backend.js
screens/AccountScreen.js
screens/ClientUserLoginForm.js
screens/ClientUsers.js
screens/ClockIn.js
screens/CreateAccFormScreen.js
screens/IntroAppScreen.js
screens/Login.js
screens/LoginScreen.js
screens/OrderForm.js
screens/OrdersSummaryRow.js
screens/Payment.js
screens/ProductFormScreen.js
screens/ProductRow.js
screens/ShiftClose.js
screens/Store.js
screens/StoreFormScreen.js
styles.js
validators.js

> refactored client and client user login
> added service charge and tax inclusive to store screen
> refactored shift close screen

Post app review refactoring and fixes.

---

actions/custom.js
actions/rangedsalesreport.js
components/EditPasswordPopUp.js
constants/Backend.js
screens/AccountScreen.js
screens/BackendErrorScreen.js
screens/ClientUserLoginForm.js
screens/ClockIn.js
screens/Login.js
screens/LoginSuccessScreen.js
screens/OrderFormII.js
screens/OrderStart.js
screens/OrdersScreen.js
screens/OrdersSummaryRow.js
screens/PrinterForm.js
screens/PrinternKDS.js
screens/SalesCharts.js
screens/SettingsScreen.js
screens/ShiftClose.js
screens/Staff.js
screens/StaffEditScreen.js
screens/StaffFormScreen.js
screens/StaffRow.js
screens/StoreFormScreen.js
screens/TablesScreen.js
screens/WorkingAreaForm.js
styles.js

> introduced several flavor of formatDate function.
> created dispatchFetchRequest function for later refactoring on all action functions to properly handle errors.
> removed obsolete item from AsyncStorage.
> added loggedIn to token and client user token.

Refactored home screen to show basic user information.

---

app.json
components/rn-elements/CheckBox.js
constants/Backend.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
screens/ManageVisualSceen.js
screens/OrderForm.js
screens/OrderFormII.js
screens/OrderStart.js
screens/OrderTopInfo.js
screens/OrdersScreen.js
screens/OrdersSummary.js
screens/Payment.js
screens/PaymentFormScreen.js
screens/ProductRow.js
screens/SettingsScreen.js
screens/TableLayoutForm.js
screens/UpdateOrder.js

> scroll to position in Order History.
> added discount by amount off.
> reflect service charge and applied discount in Payment page.
> enable scroll view in Settings screen for landscape mode.

Update order information including table and demographic data

---

components/ItemList.js
helpers/orderActions.js
locales/en.js
locales/zh.js
screens/ClockIn.js
screens/OrderDetail.js
screens/OrdersSummaryRow.js
screens/Product.js
screens/ProductEditScreen.js
screens/ProductFormScreen.js
screens/ProductRow.js
screens/ProductSelector.js
screens/StaffFormScreen.js
screens/Store.js
screens/StoreFormScreen.js
styles.js

> Added location based service feature toggle.
> Localized roles in staff screen.

Implemented product set configuration and order display.

---

locales/en.js
locales/zh.js
screens/CreateAccFormScreen.js
validators.js

1. add confirm password in create account flow done
2. 調整註冊畫面鍵盤出現時輸入框被擠壓到不見的問題

confirmPwd and KeyboardAvoidingView

---

components/DeleteBtn.js
components/RenderStepper.js
components/ThemeScrollView.js
package-lock.json
package.json
screens/NewOrderModal.js
screens/OrderFormII.js
screens/OrderItem.js
screens/OrderItemDetailEditModal.js
screens/OrderStart.js
screens/OrderTopInfo.js
screens/OrdersSummaryRow.js
screens/TablesScreen.js
styles.js
themes/ThemeContext.js

new order modal and goto order detail done

New order modal

---

App.js
actions/custom.js
components/MoneyKeyboard.js
components/RenderStepper.js
constants/Backend.js
locales/en.js
locales/zh.js
package-lock.json
package.json
screens/NewOrderModal.js
screens/OrderFormII.js
screens/OrderItemDetailEditModal.js
screens/Payment.js
screens/PaymentDiscountModal.js
screens/PaymentFormScreenTablet.js
screens/PaymentOrder.js
screens/PaymentOrderForm.js
screens/TablesScreen.js
styles.js
themes/ThemeContext.js

Pay screen

---

App.js
constants/Backend.js
constants/Colors.js
screens/OrderFormII.js
screens/OrdersSummaryRow.js
screens/ProductFormScreen.js
screens/TablesScreen.js
validators.js

1.order product status: sort and colorful
2.merge table(tablet): except completed order, drag and merge two orders
3.fix validators: input required change by global locale

RA194, RA195, RA196 

---

helpers/printerActions.js

Change printAction

---

constants/Backend.js
screens/OrderFormII.js
screens/OrdersSummaryRow.js
screens/TablesScreen.js

1. Fix : order lineitems 'PREPARED' status on phone
2. Hidden btn: “Join Table“
3. Deliver order/line items in settled state
- display deliver( upon complete btn)
- triggle api.order.settledProcess

RA199, RA212, RA226

---

screens/OrdersSummaryRow.js

fix phone screen: OrderSummaryRow.js

RA226 - fix

---

screens/OrderFormII.js
screens/RetailOrderForm.js
screens/RetailOrderSummaryScreen.js

add same function in retail ( home - quick start)

RA193 - retail mode

---

screens/OrderFormII.js

Fix order category error

---

constants/Backend.js
locales/en.js
locales/zh.js
screens/AccountScreen.js
screens/Login.js
screens/LoginScreen.js
screens/OrderDetail.js
screens/OrderFormII.js

1. Add deleted items in orderDetail
2. Add Token login method

RA218, RA225

---

locales/en.js
locales/zh.js
screens/AnnouncementsForm.js
screens/ClockIn.js
screens/MemberFormScreen.js
screens/MemberScreen.js
screens/NewOrderModal.js
screens/OrderDetail.js
screens/OrderForm.js
screens/PaymentFormScreenTablet.js
screens/PaymentOrderForm.js
screens/SpiltBillScreen.js
screens/SplitBillByHeadScreen.js

1. fix membership sign up UI
2. add localize "newOrder"
3. theme background fix

RA248, RA255, RA256

---

screens/CategoryCustomizeScreen.js
screens/OrderItem.js
screens/OrdersScreen.js
screens/ProductEditScreen.js
screens/ProductFormScreen.js
screens/StoreFormScreen.js
screens/TablesScreen.js

1. Product (237,258,262)
- fix getProductOptions() and avoid error msg
- change screen title
- Add initialValue for new inventory
2.Shift (261)
- command line 192
3.Table order(243, 266)
- Add LoadingScreen display
- Add time limit icon (control by store setting)

Product, Shift, Table order: Issue fix

---

screens/PaymentFormScreenTablet.js
screens/PaymentOrder.js

If split by item, remove delete parent order action (backend control)

Change spilt order action

---

components/PermissionCheckTouchable.js
helpers/permissionActions.js
screens/AccountScreen.js
screens/CategoryCustomizeScreen.js
screens/ReportsScreen.js

1. Add user permission check
2. fix product secondary title

RA259, RA258-mini fix

---

helpers/orderActions.js
locales/en.js
locales/zh.js
screens/OrderFormII.js
screens/OrdersSummaryRow.js

1. Print selected items when press work order
2. Add translation "Move Order"

RA271, RA274

---

screens/TablesScreen.js

Table android fix

---

constants/Backend.js
locales/en.js
locales/zh.js
screens/ClockIn.js
screens/EinvoiceStatusScreen.js
screens/ManageOffers.js
screens/OfferForm.js
screens/OrderDetail.js

1. Add trigger type to offer
2. Clock in: if location base, add distance tip
3. Add cancel invoice function

RA201, RA238, RA252

---

locales/en.js
locales/zh.js
package.json
screens/AccountScreen.js
screens/CalendarScreen.js
screens/ClockIn.js
screens/LoginScreen.js
screens/OrderFilterForm.js
screens/OrderItem.js
screens/OrdersSummaryRow.js
screens/RetailOrderSummaryScreen.js
screens/SubscriptionScreen.js
yarn.lock

1. Fix UI : dark Bg & inverse white text
2. Change translation
3. Add webview

RA263, RA280, RA273

---

components/OfferTooltip.js
locales/en.js
locales/zh.js
screens/AccountScreen.js
screens/OrderFormII.js
screens/OrderFormIII.js
screens/OrderFormIV.js
screens/OrderItemDetailEditModal.js
screens/OrdersSummaryRow.js
screens/PaymentFormScreen.js
screens/PaymentFormScreenTablet.js
screens/RetailOrderForm.js
screens/RetailOrderSummaryScreen.js
screens/TablesScreen.js

1. Display applied offer information
2. Disable Alert check when no printers
3. Fix Android input: order note edit

RA217, RA290, RA293

---

components/DateTimePicker.js
screens/CalendarScreen.js
screens/OrderFormIII.js
screens/OrderItemDetailEditModal.js
screens/RostersFormScreen.js

1. Calendar bug fix
2. Product option data type change

RA296, RA299

---

components/MenuFlatButton.js
components/OfferTooltip.js
components/PopUp.js
components/SegmentedControl.js
locales/en.js
locales/zh.js
screens/CategoryCustomizeScreen.js
screens/ClientUsers.js
screens/LoginSuccessScreen.js
screens/OfferForm.js
screens/OrderFilterForm.js
screens/OrderFormII.js
screens/OrderItem.js
screens/OrderItemDetailEditModal.js
screens/OrdersScreen.js
screens/RetailOrderForm.js
screens/RetailOrderSummaryScreen.js

1. Client users UI fix
2. Segmented UI fix(for Android)
3. OfferTootip change style
4. appliesToProducts default true
5. Add "Quick take out"
6. Order list add modifiedDate

RA203, RA287, RA294, RA298, RA300, RA301

---

screens/EinvoiceStatusScreen.js
screens/Login.js
screens/LoginScreen.js
screens/LoginSuccessScreen.js
screens/ProductRow.js

1. Avoid when ubn not exist and return error
2. Add mutiple user login modal
3. Fix Avatar props title error msg

RA307, RA309

---

screens/LoginScreen.js
screens/ProductRow.js

login localization & same label products sort filter

Mini bugs fix

---

screens/OrderFormIV.js

order phone bottom fix

---

screens/OrderDisplayScreen.js
screens/PaymentFormScreenTablet.js

1. Android request type error
2. Tablet route

Fix take out order bugs 

---

actions/custom.js
locales/en.js
locales/zh.js
screens/ShiftClose.js

1. Organize localization to root file
2. Fix formatTime

fix time type error

---

constants/Backend.js
screens/AccountScreen.js
screens/ClockIn.js
screens/LoginScreen.js
screens/LoginSuccessScreen.js
screens/OrderDisplayScreen.js
screens/StoreFormScreen.js
screens/TablesScreen.js

1. Add function:  mark all orders/lineItems prepared
2. Time card device setting

RA198, RA250

---

screens/SalesCharts.js

Fix sales chart

---

screens/LoginSuccessScreen.js
screens/Staff.js
screens/StaffFormScreen.js

Fix staff bug

---

screens/SpiltBillScreen.js
screens/SplitBillByHeadScreen.js

Fix localization

---

screens/AccountCloseConfirmForm.js
screens/ShiftDetails.js

Fix close shift

---

components/CalendarEvent.js
components/Calendars.js
constants/Backend.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
screens/CalendarScreen.js
screens/PrinterAdd.js
screens/PrinterEdit.js
screens/PrinterForm.js
screens/PrinternKDS.js
screens/ReservationConfirmScreen.js
screens/ReservationEditScreen.js
screens/ReservationFormScreen.js
screens/ReservationScreen.js

1. Reservations link with calendar
2. Edit, delete reservation
3. Fix Printer localize

RA323, RA325, RA326, RA327, RA328

---

constants/Backend.js
screens/ReservationCalendarScreen.js
screens/ReservationConfirmScreen.js
screens/ReservationEditScreen.js
screens/ReservationFormScreen.js
screens/ReservationScreen.js

1. Fix reservation date bugs
2. Add send SMS function

RA338, RA344

---

components/InputTextComponent.js
components/TableRenderCheckboxGroup.js
constants/Backend.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
screens/AccountScreen.js
screens/OrderDetail.js
screens/OrderForm.js
screens/OrderFormII.js
screens/OrdersSummaryRow.js
screens/ReservationCalendarScreen.js
screens/ReservationFormScreen.js
screens/ReservationScreen.js
screens/ReservationUpcomingForm.js
screens/ReservationUpcomingScreen.js
screens/RetailOrderForm.js
screens/RetailOrderSummaryScreen.js
screens/UpdateOrder.js

1. New screen: RA363, RA365
2. Warning fix: RA360
3. UI fix: RA357, RA366

Reservation upcoming

---

components/FocusAwareStatusBar.js

Fix Statusbar by device

---

components/FocusAwareStatusBar.js

Use modelId to get device type

Change device function

---

components/InputTextComponent.js
screens/ReservationFormScreen.js
screens/ReservationUpcomingForm.js
validators.js

Fix TextInput method

---

App.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
navigation/NavigationService.js
screens/LoginScreen.js
screens/LoginSuccessScreen.js

1. Remove bottom tab: reservation
2. Set reservation as an sub function at home

RA397, 398

---

components/ScreenHeader.js
locales/en.js
locales/zh.js
screens/AccountCloseConfirmForm.js
screens/AccountClosureForm.js
screens/CloseComplete.js
screens/EinvoiceStatusScreen.js
screens/ReservationFormScreen.js
screens/ReservationSettingForm.js
screens/ReservationUpcomingForm.js
screens/ReservationViewScreen.js
screens/ShiftClose.js

RA403, RA405~408

---

components/Calendars.js
screens/TablesScreen.js

1. Calendar day view change by timezone
2. Store & Close shift process fix

Process & style fix

---

App.js

3 type: store, retail, reservation

Fix get type

---

app.json
screens/ReservationEditScreen.js
screens/ReservationScreen.js
screens/ReservationUpcomingForm.js
screens/ReservationUpcomingScreen.js
screens/ReservationViewScreen.js

Fix notification

---

navigation/MainTabNavigator.js
screens/OrdersScreen.js

Update again when touch bottom tab

Fix shift orders search

---

screens/OrderForm.js
screens/PaymentFormScreen.js
screens/ReservationUpcomingForm.js

1. Dock the action button
2. Add time selector for waiting reservation

RA420, 422

---

screens/OrderFormII.js
screens/OrderFormIII.js
screens/OrderFormIV.js
screens/OrderItemDetailEditModal.js
screens/OrdersSummaryRow.js

1. Checkbox divide by option index
2. styles adjustment

Fix com set bugs

---

screens/OrderFormIII.js
screens/OrderItemDetailEditModal.js

Fix options error

---

screens/OrderFormIV.js

Fix phone option select

---

screens/OrderFormIII.js
screens/OrderItemDetailEditModal.js

Fix child lineitems quantity

---

components/ItemListDrag.js

1. center label & switch
2. fix hitSlop of delete btn

Adjust child label style

---

components/MoneyKeyboard.js

Fix tablet discount keyboard

---

locales/en.js
locales/zh.js
screens/ReservationCalendarScreen.js
screens/ReservationScreen.js
screens/ReservationUpcomingScreen.js
screens/ReservationViewScreen.js
screens/StoreFormScreen.js

1. Fix new account store setting validate
2. Add SMS send check when create new reservation

RA429, RA444~446

---

App.js
constants/Backend.js
helpers/loginActions.js
navigation/MainTabNavigator.js
package.json
screens/IntroAppScreen.js
screens/LoginSuccessScreen.js
styles.js
yarn.lock

1. Add Placeholder in home
2. Fix refresh token method

RA441, RA443

---

screens/OrderFormIV.js
screens/OrderItemDetailEditModal.js

If multiple selected 2 childPrd, can't send lineitem

Fix product option multiple require

---

components/TableRenderCheckboxGroup.js
constants/Backend.js
locales/en.js
locales/zh.js
screens/OrderFormII.js
screens/OrderFormIII.js
screens/OrderFormIV.js
screens/OrderItemDetailEditModal.js
screens/OrderItemMoveTableModal.js
screens/OrdersSummaryRow.js

1. Keep old state for next item edit
2. Add function: move item to other table

RA448, 452

---

components/MoneyKeyboard.js
components/PopUp.js
locales/en.js
locales/zh.js
navigation/MainTabNavigator.js
screens/AccountCloseConfirmForm.js
screens/AccountClosureForm.js
screens/OrderFormII.js
screens/OrdersSummaryRow.js
screens/ShiftDetails.js
screens/ShiftHistory.js
screens/SplitBillByAmountScreen.js

1. Add new paymentMethod sort
2. Split by amount
3. Disable click twice when split by item

RA456, 457, 470

---

screens/PaymentFormScreen.js
screens/PaymentFormScreenTablet.js
screens/PaymentOrderForm.js

Bugs left from RA471

---

locales/en.js
locales/zh.js
screens/PrinterAdd.js
screens/PrinterEdit.js
screens/PrinterForm.js
screens/PrinternKDS.js
screens/WorkingAreaAdd.js
screens/WorkingAreaEdit.js

> removed unnecessary function calls in working area and printer screens.

Added table layouts to Printer screen.
